from enum import Enum

class DeploymentStatus(str, Enum):
    DRAFT = "DRAFT"
    PROVISIONING = "PROVISIONING"
    INFRA_READY = "INFRA_READY"
    DEPLOYING = "DEPLOYING"
    CONFIGURING = "CONFIGURING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    DESTROYING = "DESTROYING"
    DESTROYED = "DESTROYED"

class OperationType(str, Enum):
    PROVISION = "PROVISION"
    DEPLOY = "DEPLOY"
    UPDATE = "UPDATE"
    DESTROY = "DESTROY"
    SUBSCRIBE = "SUBSCRIBE"

class OperationStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class RoleType(str, Enum):
    CUSTODIAN = "CUSTODIAN"
    PARTICIPANT = "PARTICIPANT"

class ComputeType(str, Enum):
    GKE = "GKE"
    CLOUD_RUN = "CLOUD_RUN"

class SubscriptionStatus(str, Enum):
    INITIATED = "INITIATED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    SUBSCRIBED = "SUBSCRIBED"
    FAILED_VERIFICATION = "FAILED_VERIFICATION"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"

class AuditActionType(str, Enum):
    DEPLOYMENT_CREATED = "DEPLOYMENT_CREATED"
    CONFIG_UPDATE = "CONFIG_UPDATE"
    INFRA_PROVISION_TRIGGERED = "INFRA_PROVISION_TRIGGERED"
    INFRA_DESTROY_TRIGGERED = "INFRA_DESTROY_TRIGGERED"
    APP_DEPLOY_TRIGGERED = "APP_DEPLOY_TRIGGERED"
    SUBSCRIPTION_INITIATED = "SUBSCRIPTION_INITIATED"